# Generated by Django 4.1.2 on 2023-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApplicantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=20)),
                ('contact_no', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('addresss', models.TextField(max_length=200)),
            ],
        ),
    ]
