# Generated by Django 4.1.2 on 2023-01-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapplicanttable',
            name='addresss',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
